/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnswerFrame.java
 *
 * Created on 2013-11-24, 20:22:57
 */
package edu.umass.rio.gpm.ui;

import java.awt.Dimension;

/**
 *
 * @author jujuhoo
 */
public class AnswerFrame extends javax.swing.JFrame {

    /** Creates new form AnswerFrame */
    public AnswerFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        answerPanel = new edu.umass.rio.gpm.ui.ZPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        answerPanel.setAutoscrolls(true);
        answerPanel.setName("answerPanel"); // NOI18N

        javax.swing.GroupLayout answerPanelLayout = new javax.swing.GroupLayout(answerPanel);
        answerPanel.setLayout(answerPanelLayout);
        answerPanelLayout.setHorizontalGroup(
            answerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        answerPanelLayout.setVerticalGroup(
            answerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(answerPanel);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setImage(String path){
        this.answerPanel.setImagePath(path);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.umass.rio.gpm.ui.ZPanel answerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
